# see https://github.com/viamrobotics/build-action for help
on:
  release:
    types:
      - released
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download viam-cli
        run: |
          curl -L -o ./viam-cli "https://storage.googleapis.com/packages.viam.com/apps/viam-cli/viam-cli-latest-linux-amd64"
          chmod +x ./viam-cli
      - name: Update module meta.json in registry
        env:
          API_KEY_ID: ${{ secrets.viam_key_id }}
          API_KEY: ${{ secrets.viam_key_value }}
        run: |
          ./viam-cli login api-key --key-id "$API_KEY_ID" --key "$API_KEY"
          ./viam-cli module update
      - uses: viamrobotics/build-action@v1
        with:
          version: ${{ github.ref_name }}
          ref: ${{ github.sha }}
          key-id: ${{ secrets.viam_key_id }}
          key-value: ${{ secrets.viam_key_value }}
